repos:
  - repo: local
    hooks:
      - id: format
        name: format
        language: system
        pass_filenames: false
        entry: cargo fmt --all -- --check
      - id: check
        name: check
        language: system
        pass_filenames: false
        entry: cargo check --tests
      - id: clippy
        name: clippy
        language: system
        pass_filenames: false
        entry: cargo clippy -- -D warnings
